version: '3'
services:
  postgres:
    image: postgres:11.6
    container_name: postgres-boilerplate
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=rebel
      - POSTGRES_PASSWORD=rebel
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql
